apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: spotify
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  clusterIP: None

